import { superOver } from "../server/superOver.js";

let sample1 = [
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "2",
    ball: "2",
    batsman: "SV Samson",
    non_striker: "KK Nair",
    bowler: "T Natarajan",
    is_super_over: "0",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "0",
    extra_runs: "0",
    total_runs: "0",
    player_dismissed: "",
    dismissal_kind: "",
    fielder: "",
  },
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "2",
    ball: "2",
    batsman: "SV Samson",
    non_striker: "KK Nair",
    bowler: "T Natarajan",
    is_super_over: "0",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "0",
    extra_runs: "0",
    total_runs: "0",
    player_dismissed: "",
    dismissal_kind: "",
    fielder: "",
  },
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "2",
    ball: "2",
    batsman: "SV Samson",
    non_striker: "KK Nair",
    bowler: "T Natarajan",
    is_super_over: "0",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "0",
    extra_runs: "0",
    total_runs: "0",
    player_dismissed: "",
    dismissal_kind: "",
    fielder: "",
  },
];

test("Checking if there is no super over in deliveries data(branch coverage=14%)", () => {
  expect(superOver(sample1)).toEqual({});
});

let sample2 = [
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "2",
    ball: "2",
    batsman: "SV Samson",
    non_striker: "KK Nair",
    bowler: "T Natarajan",
    is_super_over: "1",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "2",
    extra_runs: "0",
    total_runs: "2",
    player_dismissed: "",
    dismissal_kind: "",
    fielder: "",
  },
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "2",
    ball: "2",
    batsman: "SV Samson",
    non_striker: "KK Nair",
    bowler: "T Natarajan",
    is_super_over: "1",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "0",
    extra_runs: "0",
    total_runs: "0",
    player_dismissed: "",
    dismissal_kind: "",
    fielder: "",
  },
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "2",
    ball: "2",
    batsman: "SV Samson",
    non_striker: "KK Nair",
    bowler: "T Natarajan",
    is_super_over: "1",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "0",
    extra_runs: "0",
    total_runs: "0",
    player_dismissed: "",
    dismissal_kind: "",
    fielder: "",
  },
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "3",
    ball: "5",
    batsman: "SV Samson",
    non_striker: "KK Nair",
    bowler: "Sandeep Sharma",
    is_super_over: "0",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "0",
    extra_runs: "0",
    total_runs: "0",
    player_dismissed: "SV Samson",
    dismissal_kind: "caught",
    fielder: "MM Sharma",
  },
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "3",
    ball: "6",
    batsman: "KK Nair",
    non_striker: "SS Iyer",
    bowler: "Sandeep Sharma",
    is_super_over: "0",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "0",
    extra_runs: "0",
    total_runs: "0",
    player_dismissed: "",
    dismissal_kind: "",
    fielder: "",
  },
];
test("Only 1 bowler bowled superover", () => {
  expect(superOver(sample2)).toEqual({ "T Natarajan": 4.0 });
});

let sample3 = [
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "2",
    ball: "2",
    batsman: "SV Samson",
    non_striker: "KK Nair",
    bowler: "T Natarajan",
    is_super_over: "1",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "6",
    penalty_runs: "0",
    batsman_runs: "0",
    extra_runs: "0",
    total_runs: "6",
    player_dismissed: "",
    dismissal_kind: "",
    fielder: "",
  },
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "2",
    ball: "2",
    batsman: "SV Samson",
    non_striker: "KK Nair",
    bowler: "T Natarajan",
    is_super_over: "1",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "1",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "4",
    extra_runs: "0",
    total_runs: "5",
    player_dismissed: "",
    dismissal_kind: "",
    fielder: "",
  },
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "2",
    ball: "2",
    batsman: "SV Samson",
    non_striker: "KK Nair",
    bowler: "T Natarajan",
    is_super_over: "1",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "0",
    extra_runs: "0",
    total_runs: "0",
    player_dismissed: "",
    dismissal_kind: "",
    fielder: "",
  },
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "3",
    ball: "5",
    batsman: "SV Samson",
    non_striker: "KK Nair",
    bowler: "Sandeep Sharma",
    is_super_over: "0",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "0",
    extra_runs: "0",
    total_runs: "0",
    player_dismissed: "SV Samson",
    dismissal_kind: "caught",
    fielder: "MM Sharma",
  },
  {
    match_id: "35",
    inning: "1",
    batting_team: "Delhi Daredevils",
    bowling_team: "Kings XI Punjab",
    over: "3",
    ball: "6",
    batsman: "KK Nair",
    non_striker: "SS Iyer",
    bowler: "Sandeep Sharma",
    is_super_over: "0",
    wide_runs: "0",
    bye_runs: "0",
    legbye_runs: "0",
    noball_runs: "0",
    penalty_runs: "0",
    batsman_runs: "0",
    extra_runs: "0",
    total_runs: "0",
    player_dismissed: "",
    dismissal_kind: "",
    fielder: "",
  },
];

test("no ball in superover(ball not counted in bowler's figure but run does) and a leg bye run extra (not included in bowler's figure)", () => {
  expect(superOver(sample3)).toEqual({ "T Natarajan": 30.0 });
});
